Progress on Upgrading Spectral Library
capstone-coal/pycoal pull request #140
Opened 2018-03-15 15:03 UTC by bdegley4789

This is where I am on Issue #105 @lewismc 
I used the save() function for creating .hdr and .sli files like the AsterConversion and link you sent showed. But I'm not sure how I would query the .txt files. I may be able to do it in python as a .csv, I tried here just converting .db but that doesn't really work for query as far as I can tell

2018-03-15 15:04 UTC, bdegley4789 commented
This pull request doesn't need to be accepted. I just wanted to show you where I am at, so we can discuss in our meeting

2018-03-22 20:35 UTC, lewismc commented on examples/convert_to_aster.py
> +# Copyright (C) 2018 COAL Developers
See other copyright headers and make sure the dates are idential

2018-03-22 21:01 UTC, lewismc requested changes
@bdegley4789 see my comments in their entirety. Once you've seen them, close this pull request and start again. Next time around, please follow the logic that I give you when we have our meetings.

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +@copyright:  2018 COAL Developers. All rights reserved.
See other copyright headers and make sure the dates are idential

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +Spectral Version 7 .txt file converted to ASTER .txt file format
```Spectral Version 7``` doesn't refer to anything specific... make it specific.

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> -# Copyright (C) 2017-2018 COAL Developers
Why has this been removed?

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +        Library Version 2.0 <https://speclib.jpl.nasa.gov/>`_ converted with
Why have you reverted this?

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +        Library Version 2.0 into ENVI format.
Why have you reverted this?

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +Spectral Version 7 .txt file converted to ASTER .txt file format
Additionally, **THERE IS NO ASTER .txt FILE FORMAT**... the input is a DB file. I've already explained this several times.

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +from argparse import ArgumentParser
You are not using this import... remove it

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +from argparse import RawDescriptionHelpFormatter
You are not using this import... remove it

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +import sys
Remove any unused imports... this is basic stuff.

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +library_filename = 'splib07a_Alizarin_crimson_(dk)_GDS780_ASDFRa_AREF.txt'
Where does this file come from?

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +    for i, l in enumerate(f):
Why are you creating the variables ```i``` and ```l``` here?

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +nameTemp = f.readline()
Variable ```nameTemp``` is a terrible name for this variable. Please see the [basics of variable naming in Python](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Python_and_Ruby)

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +x = open('2.txt','w')
```2.txt``` is a ridiculous name for any file however seeing as it is a _temporary_ file AND you clean it up I suppose this is OK.

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +    num = round(num,4)
What is your decision to round these floating point numbers?

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +f.write('Particle Size:  Solid\n')
This all looks like garbage to me. I don't understand why you are deciding to write static final string values for certain fields here.

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +#!/usr/bin/python
This is not even a generic file for it to be named ```convert_to_aster.py```... look at the code you've provided. It is intrinsically tied to a very specific spectra... how can this be generic?

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +
Why have you added two lines on the bottom?

2018-03-22 21:01 UTC, lewismc commented on examples/convert_to_aster.py
> +os.rename(library_filename,library_filename + '.spectrum.txt')
Why is this filename now called ```blah.spectrum.txt```? It has nothing to do with a spectrum

2018-03-22 21:01 UTC, lewismc commented on examples/example_splib07.py
> +# Copyright (C) 2018 COAL Developers
Look at every other file header.... make sure they match identically.

2018-03-22 21:01 UTC, lewismc commented on examples/example_splib07.py
> +example_sam -- Plot Spectral Angles
This is NOT ```example_sam``` and you are NOT plotting spectral angles.

2018-03-22 21:01 UTC, lewismc commented on examples/example_splib07.py
> +@copyright:  2018 COAL Developers. All rights reserved.
Make sure file headers are identical.

2018-03-22 21:01 UTC, lewismc commented on examples/example_splib07.py
> +# load library
Why do you have all of this commented out code? Either use it in the implementation or remove it.

2018-03-22 21:01 UTC, lewismc commented on examples/splib07_convert.py
> +# Copyright (C) 2018 COAL Developers
Make sure license headers are identical.

2018-03-22 21:01 UTC, lewismc commented on examples/splib07_convert.py
> +Spectral Version 7 .txt file converted to ASTER .txt file format
See previous comment

2018-03-22 21:01 UTC, lewismc commented on examples/splib07_convert.py
> +@copyright:  2018 COAL Developers. All rights reserved.
See previous comment

2018-03-22 21:01 UTC, lewismc commented on examples/splib07_convert.py
> +import logging
Remove ALL unused logging.

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            ASTER Library Version 2.0 .txt files
Hyperlink ASTER

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            This class provides a method for converting Spectral .txt files into
Hyperlink USGS Spectral Library Version 7

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            This class method converts a Spectral version 7 .txt file into
Hyperlink USGS Spectral Library Version 7

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            an ASTER Library Version 2.0 .spectrum.txt file
This comment is useless as no-ne knows what a spectrum.txt file is

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            Spectral Library Version 7 can be downloaded here https://speclab.cr.usgs.gov/spectral-lib.html
Use hyperlink markup.

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            1. Move all .txt files in Spectral Library Version 7 to one directory named 'usgs_splib07_modified'
This logic is flawed... the user will be sitting waiting doing this forever. The Python code should take care of doing this. It is called automation.

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            2. Place this directory('usgs_splib07_modified') you just made in the pycoal/examples directory
Why in Gods name would we ever want to do that.
**WE ARE TRYING TO USE THIS TOOLKIT FROM THE COMMAND LINE**... come on.

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            3. run splib07_convert.py in the pycoal/examples directory
No no no

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            4. run example_splib07.py in the pycoal/examples directory
No no no this is riduculous

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +            5. s07av95a_envi.hdr and s07av95a_envi.sli will be generated
Where will they be generated? Which directory? You NEED TO COMMENT YOUR CODE.

2018-03-22 21:01 UTC, lewismc commented on pycoal/mineral.py
> +        f.write('Origin: Spectra obtained from the Noncoventional Exploitation Factors\n')
This is useless and only works for one specific file. This needs to change entirely.

2018-03-23 00:00 UTC, bdegley4789 commented
Hey Lewis,

I will definitely update the headers, add comments to my code and remove any commented out code like you said.

I also agree it is a bad method to have users manually move files

I can use os.walk to loop through directories so users can do everything from the command line. 
I tried doing this but couldn't figure it out so I just moved all the .txt files to one directory and used os.listdir() for the time being.
I will work on incorporating these changes

2018-03-23 00:03 UTC, bdegley4789 commented
There is confusion on the rest of my code.

The AsterConversion class in mineral.py has two ways of working.
One way is what you talk about with input as a DB file which you mentioned in your comment
The other way is by getting a directory of .spectrum.txt files and generating a .db file

Look at AsterConversion class in mineral.py on Line 332 mineral.py 
https://github.com/capstone-coal/pycoal/blob/41bed1807a2d1d798c5bc8ee79a4b5cc336b7b8a/pycoal/mineral.py#L332

For this method I used the Second way
1) Taking the Aster Library which is all .spectrum.txt files
2) Then generates a .db file from the .spectrum.txt files
3) Then generates a .sli and .hdr file from the .db file

What I did is change the Spectral .txt files to match the Aster .spectrum.txt file format, while still using it's original name and values.
Then I used the method of 2 & 3 above to generate the .sli and .hdr files for Spectral Library Version 7

Remember, our current AsterConverion only looks at the name and the query for the x column which is the wavelength values which I put in that same column.

Line 355 mineral.py
https://github.com/capstone-coal/pycoal/blob/41bed1807a2d1d798c5bc8ee79a4b5cc336b7b8a/pycoal/mineral.py#L355 

The other values that I put in are never used for .sli and .hdr creation in regards to your last inline comment. So, this method will work for all files

2018-03-23 00:08 UTC, bdegley4789 commented
convert_to_aster.py was used for testing the convert function and you are correct it only works on one file, that file is just a random file from the spectral library I used to work with. 
That is why I didn't include convert_to_aster.py in those 5 steps I wrote.

splib07_convert.py will work on the entire directory you provide

mineral.py line 402
https://github.com/bdegley4789/pycoal/blob/7b10aa9592ea913a4816cdab49aa2a3754b3a64f/pycoal/mineral.py#L402
https://github.com/bdegley4789/pycoal/blob/7b10aa9592ea913a4816cdab49aa2a3754b3a64f/pycoal/mineral.py#L403
https://github.com/bdegley4789/pycoal/blob/7b10aa9592ea913a4816cdab49aa2a3754b3a64f/pycoal/mineral.py#L404

That for loop and variables i and l are used to find the number of lines in the file so I know how much data I need to record and store

The code does work on every .txt file in the Spectral Library which I tested. 
If you look at the hdr files for splib06 and splib07 I staged in https://drive.google.com/drive/folders/1YVhdLxvrZE3eC97OEXathLMJRgWt8haO they are the same format. 
I built this method around using the .save function you had sent me and looking at the Aster conversion code provided and refrenced in the issue discussed in the meetings.
I might need to tweek the name of the mineral values and edit the code in mining, mineral and environment.py to look for the new names of the spectral library 7 minerals
Other than that it looks like it is all working correctly with the method I have used. I think we should go forward with this after I make the changes mentioned at the top

2018-03-23 00:21 UTC, bdegley4789 commented
I'll wait to close this pull request, if you still want to, after reviewing my comments

2018-03-23 04:05 UTC, lewismc commented
@bdegley4789 thanks for considering the comments and criticisms.

> I will definitely update the headers, add comments to my code and remove any commented out code like you said.

Yes please go ahead and do this before we move forward. Basically lets start from there.

2018-03-23 07:48 UTC, closed without merging