ISSUE-105 Upgrade to use USGS Spectral Library Version 7
capstone-coal/pycoal pull request #142
Opened 2018-04-12 05:43 UTC by bdegley4789

2018-04-12 19:23 UTC, lewismc commented
@bdegley4789 please merge master branch into this PR and push. This is why the tests are failing. Thank you.

2018-04-13 08:25 UTC, bdegley4789 commented
@lewismc ok, I have merge your changes to the docker file. Hopefully that fixes the ci/dockcloud

2018-04-18 18:11 UTC, lewismc requested changes
@bdegley4789 by introducing ```importlib`` you are breaking the build... see the tests
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/capstone-coal/pycoal/pycoal/tests/mineral_test.py", line 25, in <module>
    from pycoal import mineral
  File "/home/travis/build/capstone-coal/pycoal/pycoal/mineral.py", line 29, in <module>
    importlib.reload(sys)
AttributeError: 'module' object has no attribute 'reload'
```
Please fix and address comments, thanks.

2018-04-18 18:11 UTC, lewismc commented on examples/example_spectral07.py
> +from sys import path
Remove this import, you've already imported ```sys``` and then use it in line 44 as per ```sys.path.insert(0, '../pycoal')```

2018-04-18 20:16 UTC, lewismc commented
@bdegley4789 please always [test your code locally](https://github.com/capstone-coal/pycoal#tests) before submitting a PR.

2018-04-18 20:21 UTC, bdegley4789 commented
Yes, sorry about that. I'm working on my work computer right now and don't have all the dependencies for pycoal installed. 
I can't remember why I have importlib.reload(sys) but I recall adding it to get something to work. I'll test later when I get back home

2018-04-18 20:34 UTC, lewismc commented
> Yes, sorry about that...

No problem, I'm just trying to make your life a bit easier rather than you always seeing the failing CI builds for your pull requests.

2018-04-19 05:56 UTC, bdegley4789 commented
nosetests now passes
![screen shot 2018-04-18 at 10 55 58 pm](https://user-images.githubusercontent.com/25111791/38973647-bf15a91c-435b-11e8-884b-a63e9097eda7.png)

2018-04-19 06:13 UTC, bdegley4789 commented
I think travis-ci wants tests for the classes I created in mineral.py
I started on that yesterday. Will submit either tomorrow or friday
I'll close this pr for now since travis-ci is still failing

2018-04-19 06:13 UTC, closed without merging

2018-04-24 15:26 UTC, lewismc commented
@bdegley4789 any updates here/ Thanks

2018-04-24 16:13 UTC, bdegley4789 commented
@lewismc I'm still doing the tests for my conversion code, I'll have a new pull request with tests of my code up tonight or tomorrow. I also started a mineral classification with s07 envi .sli and .hdr on our default example on Sunday, it is still running

2018-04-24 16:16 UTC, lewismc commented
ACK ok thank you for the update I appreciate it.