ISSUE-122 Classifier Callback
capstone-coal/pycoal pull request #145
Opened 2018-04-19 09:11 UTC by thomkenn

Early tentative formatting for final classifier callback, add an argument for the classifier type and allow it to process the image based on that.

2018-04-19 14:34 UTC, lewismc requested changes
Hi @thomkenn thank you fro submitting pull request. Please consider my feedback. Thanks.

2018-04-19 14:34 UTC, lewismc commented on pycoal/mineral.py
> +    def classify_image(self, image_file_name, classified_file_name, classifier_type=None):
Change this parameter to default of ```SAM```

2018-04-19 14:34 UTC, lewismc commented on pycoal/mineral.py
> +            classifier_type (str):      Classifier type used
Augment this with the list of possible classifier options e.g. SAM, GML, KMeans, MDC (MahalanobisDistanceClassifier), etc. More classifiers can be seen at http://www.spectralpython.net/class_func_glossary.html#classification

2018-04-19 14:34 UTC, lewismc commented on pycoal/mineral.py
> +        if classifier_type == None or classifier_type == 'SAM':
Default value should always be SAM, remove reference to None

2018-04-19 14:34 UTC, lewismc commented on pycoal/mineral.py
> +            # the following is the method layed out in the spectral python documentation, needs to be converted to work with our formatting
Don't just comment that it needs to be converted... actually go ahead and convert it.

2018-04-19 14:34 UTC, lewismc commented on pycoal/mineral.py
> +            # the following is the method layed out in the spectral python documentation, needs to be converted to work with our formatting
Same applies here... go ahead and implement the classification don't just say you will... do it.

2018-04-24 03:22 UTC, lewismc commented
Hi @thomkenn any update? Haven;t heard anything in almost a week! Are you stuck with something?

2018-04-26 21:52 UTC, lewismc commented
@thomkenn PING this issue hasn't been touched in over a week. We agreed that the communication aspect of this work would improve... do you have a progress update please? Thanks

2018-04-27 03:44 UTC, thomkenn commented
Ill admit, im having some issue with this section thats taking me a bit longer than i had anticipated. The different classifier callbacks are going to have different return types and require different arguments, and the part about 'training initialization' is proving kind of difficult, im just trying to figure out how to work that into the function and still maintain its place within the rest of the project. This is my top priority right now, but ill strive for better communication in this pivotal time. I can do a quick pull request updating the stuff you identified earlier, and once i have my plan for dealing with the earlier problems i can push those as well

2018-04-27 04:17 UTC, lewismc commented
> Ill admit, im having some issue with this section thats taking me a bit longer than i had anticipated. 

When we discussed what your commitments were going to be as per the requirements document, I stated that, based on previous performance, these issues would take longer than both you and Bryce thought they would. 

> The different classifier callbacks are going to have different return types and require different arguments, and the part about 'training initialization' is proving kind of difficult, im just trying to figure out how to work that into the function and still maintain its place within the rest of the project. 

It would have been good if you had communicated this earlier to be honest. We are 8 days on from my initial feedback and it doesn't look like anything further has been achieved. Please let me know if things are "...proving kind of difficult" and we can discuss them here.
 
> This is my top priority right now, but ill strive for better communication in this pivotal time.

The only way that we are going to get the pull requests to an acceptable state is if you communicate with me. There is unfortunately no other way. We discussed this at the previous meeting with Kevin and it is imperative we keep the communication a priority.

> I can do a quick pull request updating the stuff you identified earlier, and once i have my plan for dealing with the earlier problems i can push those as well

Yes please do the quick pull request and I will review again then we can iterate.

I want to say the same thing to you as I did to Bryce, ALWAYS test your pull request before submitting. This is a base requirement for any source code contribution. If the proposed code edit breaks the unit tests then it is unacceptable in any Software project anywhere. The same is true here and contributions need to ensure both backwards compatibility as well as ensuring tests pass...

Please tag me once you've submitted your quick pull request. We will take it from there.

2018-05-02 02:50 UTC, lewismc commented
PING @thomkenn

2018-05-02 02:51 UTC, lewismc commented
@EvandroCT please take a look at this PR and see if your NN plans would fit in here. Thank you

2018-05-02 15:27 UTC, lewismc commented
Kenny, what is the issue you are having here? We need to hash this out... 
I’m not understanding what the issue is here. You need to communicate what the issue is.

2018-05-02 20:38 UTC, lewismc commented
Take a look at the comments... you've not addressed them. If this is not done by Thursday morning I will just do it myself.

2018-05-03 11:18 UTC, thomkenn commented
The most recent commit should address the quick issues we discussed earlier, this was the 'quick fix' i mentioned, just taking care of the the sam being the default option as well as the removing of the 'none' item. The other issues will require a reworking of the funciton as we know it to include the 'training' for  and a way to pass different arguments for different classifiers

2018-05-03 15:30 UTC, lewismc commented
@thomkenn 

> The most recent commit should address the quick issues we discussed earlier, this was the 'quick fix' i mentioned, just taking care of the the sam being the default option as well as the removing of the 'none' item.

This is not exactly quick if it took a week to edit around 4 lines of code!

> The other issues will require a reworking of the funciton as we know it to include the 'training' that these classifier methods talk about and a way to pass different arguments for different classifiers

Is there any reason that this has turned out to be so difficult? It is pretty straight forward work with most of it already done.... Additionally, your PR breaks the existing tests... you've not dealt with that either. 

Can you please again consider that this is meant to be 8 hours worth of work. It's taken you 2 full weeks to submit a pull request which covers about 5 or so actual lines of source code. The rest is formatting. I don't understand what the hold up is here and you are not explaining it to me either so I am not able to assess what the real issue is. Please try and help me out here.

2018-05-11 15:32 UTC, lewismc commented
Closing this off.

2018-05-11 15:32 UTC, closed without merging