Issue 165
capstone-coal/pycoal pull request #171
Opened 2019-10-03 22:32 UTC by Lactem

Closes #165 . This PR cleans up examples by using shared variables from constants.py, including the new option to only classify a subset of an image. I added more comments with links to the previously-used image and a new, smaller image that I added from around Hawaii. When using the new subset option set to 75X75, the program takes less than 15 minutes (even as low as 10 minutes). I also verified that the classified image that example_mineral.py outputs is still viewable in QGIS when using the subset options. Although the image is pretty small, it serves as a product that users can play around with in QGIS.

2019-10-03 23:42 UTC, lewismc commented
@Lactem thanks for this, does it reduce running time for examples?

2019-10-04 00:54 UTC, Lactem commented
@lewismc yes, it reduces runtime for the mineral example (mining and environment were already super fast) by only classifying a subset of the image.

2019-10-08 21:39 UTC, Lactem commented
@lewismc is this okay to merge?

2019-10-11 20:00 UTC, lewismc requested changes
Please address trivial comments @Lactem thank you this looks great.

2019-10-11 20:00 UTC, lewismc commented on examples/constants.py
> +from spectral import BandInfo
Please include license header. See other files for examples.

2019-10-11 20:00 UTC, lewismc commented on examples/constants.py
> +# Use your browser to download it by navigating to the link. Then move the move the file into the examples directory
Please remove additional verbage "Then move the move the " --> "Then move the ..."

2019-10-11 20:00 UTC, lewismc commented on examples/constants.py
> +# If you want to only classify a subset of the image, specify the range of rows and columns to classify.
I really like the way you've introduced this into the examples. It makes a lot of sense. It would be great ti demonstrate this functionality through a Jupyter notebook.

2019-10-11 20:00 UTC, lewismc commented on examples/example_environment.py
> +    """Run environment correlation.
Thank you for introducing function strings. :)

2019-10-16 21:32 UTC, theoilie commented
@lewismc Thank you for the feedback. I addressed your suggestions and am wrapping up everything else before the break.

2019-10-17 16:38 UTC, lewismc commented
+1 please merge thanks

2019-10-17 16:38 UTC, merged