ISSUE-177 Parallelize SAM algorithm in mineraly.py using Joblib
capstone-coal/pycoal pull request #181
Opened 2019-10-29 17:29 UTC by aheermann

Adds joblib functionality to mineral.py as specified in #177. Will be one possible parallelization option that can be specified in config file

2019-10-29 21:00 UTC, lewismc commented
@aheermann thanks for opening this PR. Please resolve above conflicts. Thank you.

2019-10-29 21:09 UTC, lewismc requested changes
Hi @aheermann thanks for posting your PR. Please consider and address the comments in my review.

2019-10-29 21:09 UTC, lewismc commented on pycoal/mineral.py
> +from joblib import Parallel, delayed
joblib needs to be added to [setup.py](https://github.com/capstone-coal/pycoal/blob/master/setup.py#L38)

2019-10-29 21:09 UTC, lewismc commented on pycoal/mineral.py
> +def CalculatePixel(pixel, x, y, classified, library, threshold, resample, scores_file_name):
Provide documentation for the function. An example can be found [here](https://github.com/capstone-coal/pycoal/blob/master/pycoal/mineral.py#L39-L66).

2019-10-29 21:09 UTC, lewismc commented on pycoal/mineral.py
> +def CalculatePixel(pixel, x, y, classified, library, threshold, resample, scores_file_name):
Also, let think about whether `CalculatePixel` is a suitable name for the function. It appears to me it is _**calculating a confidence value of a classifed pixel**_?

2019-10-29 21:09 UTC, lewismc commented on pycoal/mineral.py
> +        # get confidence value of the classied pixel
Spelling confidence value of the _**classied**_ pixel

2019-10-29 21:09 UTC, lewismc commented on pycoal/mineral.py
> +        # angles = SpectralAngleReplacement(resampled_pixel[numpy.newaxis, numpy.newaxis, ...], library.spectra)
If not in use please remove.

2019-10-29 21:09 UTC, lewismc commented on pycoal/mineral.py
> +        scoredJobLib = numpy.zeros(shape=(M,N), dtype=numpy.float64)
Please follow variable naming conventions defined in PEP8 e.g. `scored_job_lib`

2019-10-29 21:09 UTC, lewismc commented on pycoal/mineral.py
> +    print("Time to run: {} seconds".format(seconds))
Please redirect to logging. An example can be seen [here](https://github.com/capstone-coal/pycoal/blob/master/pycoal/mineral.py#L87).

2019-10-29 21:10 UTC, lewismc commented on pycoal/mineral.py
> +            if scoredSingle[k] is scoredSingle[k]:
Please follow variable naming conventions defined in PEP8 e.g. `scored_single`

2019-10-29 21:10 UTC, lewismc commented on pycoal/mineral.py
> +                scoredJobLib[i][j] = scoredSingle[k]
same here

2019-10-30 17:10 UTC, lewismc commented
@aheermann this is much better. Thanks for updating.
Please see above, specifically resolve conflict(s) in `pycoal/mineral.py`. 
Additionally, now that #161 is addressed via #178 you should merge your branch with master. All of the CI check above need to pass before we merge this into master.
Please let me know when I can test this out... right now I can't.
Thank you

2019-10-30 23:03 UTC, lewismc commented
Excellent @aheermann this looks much better.
Can you please scope out the [test regressions](https://travis-ci.org/capstone-coal/pycoal/builds/605232345?utm_source=github_status).
We can discuss this on Friday if you want... I will investigate in the meantime as well.

2019-10-31 14:29 UTC, lewismc approved these changes

2019-10-31 14:30 UTC, lewismc commented
I'm going to pull the code locally @aheermann and test. Please standby before merging thank you. Excellent job.

2019-11-07 19:36 UTC, lewismc commented
@capstone-coal/19-usc-capstone-team please be in a position to discuss and compare results of this review by tomorrows meeting. Thank you all in advance.

2019-11-14 15:10 UTC, lewismc commented
@aheermann please update this PR to resolve conflict. 

@capstone-coal/19-usc-capstone-team has anyone else tested this PR out?

2019-11-14 17:41 UTC, Luner commented
During our meeting I believe @aheermann mentioned looking into the issues involving the memory leak with joblib.  He mentioned that there is a known issue within the library.

2019-11-17 04:36 UTC, lewismc commented
@aheermann is this ready too be tested again then? Thanks for pushing most recent commit.

2019-11-20 02:32 UTC, lewismc commented
PING here... do you have a status update please?

2019-11-20 04:58 UTC, aheermann commented
@lewismc, this should have fixed the memory leak, as long as you make sure you have psutil installed. Past that, I imagine this branch will not be merged to master, but instead be combined with the pytorch one, for the config file branch.

2019-11-20 17:42 UTC, lewismc commented
@aheermann I'll test this right now and provide feedback.

> Past that, I imagine this branch will not be merged to master, but instead be combined with the pytorch one, for the config file branch.

No let's merge this one first. We can then update #199 and finally #198

2019-11-20 18:40 UTC, lewismc commented
BTW, installation on < python: stable 3.7.5  resulted in failure. Upgrading to Python 3.7.5 fixed that. Just in case anyone tries.

2019-11-21 02:34 UTC, lewismc commented
Hi @aheermann this has fixed the issue. See below for log
```
2019-11-20 10:41:33,058 Starting mineral classification with input file 'avng.jpl.nasa.gov/AVNG_2015_data_distribution/L2/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img.hdr' and spectral library '../pycoal/tests/s07_AV95_envi.hdr'.
2019-11-20 10:41:33,058 Instantiated Mineral Classifier with following specification: -classifier function 'SAM'
2019-11-20 10:41:33,058 Starting generation of three-band RGB image from input file: 'avng.jpl.nasa.gov/AVNG_2015_data_distribution/L2/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img.hdr' with following RGB values R: '680.0', G: '532.5', B: '472.5'
2019-11-20 10:41:41,134 Saving RGB image as 'ang20150420t182050_corr_v1e_img_rgb.hdr'
2019-11-20 10:41:41,254 Completed RGB image generation. Time elapsed: '0:00:08'
2019-11-20 10:41:41,302 Starting Mineral Classification for image 'avng.jpl.nasa.gov/AVNG_2015_data_distribution/L2/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img.hdr', saving classified image to 'ang20150420t182050_corr_v1e_img_class.hdr'
2019-11-20 10:41:41,384 Classifying a 14674X739 image
2019-11-20 18:26:23,455 Completed Mineral Classification. Time elapsed: '7:44:42'
```
Excellent work here. If we take into consideration that the initial processing time was well over a day... or maybe even longer, then this represents a huge speedup. I'm going to go ahead and merge this into master branch. Excellent work.

2019-11-21 02:35 UTC, merged