Update config file logic, tests
capstone-coal/pycoal pull request #201
Opened 2019-11-23 06:43 UTC by mjn0898

allow config file object to be passed into __init__

2019-11-23 07:04 UTC, lewismc commented on examples/example_mineral.py
> +    config_filename = os.path.join(os.path.dirname(__file__),  "..", "pycoal", "config.ini")
This logic shoud not exist in the example... instead it should be pushed into the implementing Class invocation e.g.  `MineralClassification`

2019-11-23 07:05 UTC, lewismc requested changes
Please address comments
Also, please provide unit tests for the following
* incorrect paths
* garbled, garbage config values
Thanks

2019-11-23 07:09 UTC, mjn0898 commented
The tests are in progress, I just didn't have time to do them today. 
I am a bit confused on wanting that logic in the class invocation because you wanted the config file to be passed in as a parameter to the __init__ function, which is why I now pass in a file object which I have to create elsewhere.

2019-11-23 08:59 UTC, lewismc commented
> The tests are in progress, I just didn't have time to do them today.

No problem. That's fine. I understand.

> I am a bit confused on wanting that logic in the class invocation because you wanted the config file to be passed in as a parameter to the init function, which is why I now pass in a file object which I have to create elsewhere.

Here's what I think would make a sensible API
1) augment the pycoal-mineral CLI [options](https://github.com/capstone-coal/pycoal/blob/master/pycoal/cli/mineral.py#L43-L54) to include an option for a configuration file,
2) augment the [MineralClassification __init__ function](https://github.com/capstone-coal/pycoal/blob/master/pycoal/mineral.py#L315) such that, again, it includes an option for a configuration file. In this case the `os.path.join(os.path.dirname(__file__)...` logic should reside within `MineralClassification __init__` because it may not be called from the example, it may be called from somewhere else e.g. another Python script or pycoal-mineral CLI.

Does that make sense?

2019-11-23 09:00 UTC, lewismc commented
Also, please always label your issues correctly and assign them to the current project. Thanks @mjn0898  good work.

2019-11-25 03:39 UTC, lewismc requested changes
Thanks for the PR, please see my comments.

2019-11-25 03:39 UTC, lewismc commented on pycoal/cli/mineral.py
> +                        help="Configuration File Name")
The help message could be improved here detailing what the options are e.g. relative, absolute and what the  default is.

2019-11-25 03:39 UTC, lewismc commented on pycoal/mineral.py
> +    def __init__(self, algorithm=SAM_pytorch, config_file=None, **kwargs):
Is it `None` or is it `config.uni`?

2019-11-25 03:41 UTC, lewismc commented
Also, @mjn0898 please address the DeepSource issues. Thanks

2019-11-25 07:24 UTC, mjn0898 commented
I fixed the deepsource issues. As for the build errors due to some new tests failing, most of the errors are due to the new algorithm functions not being up to date on this branch.

2019-11-25 15:10 UTC, lewismc commented
@mjn0898 this is looking much better.

> As for the build errors due to some new tests failing, most of the errors are due to the new algorithm functions not being up to date on this branch.

Well then please just use the following annotation for the time being
```
@unittest.skip("reason for skipping")
```
See the follosing SO post - https://stackoverflow.com/questions/2066508/disable-individual-python-unit-tests-temporarily
Thanks

2019-11-26 04:58 UTC, merged

2019-11-26 04:59 UTC, lewismc commented
Thank you @mjn0898 good work on this branch. Some notes for your consideration
* please always create an issue before you create the pull request. This should describe the scope of the work. Your commit messages should also reflect this scope.
* on commit messages, please see the following - https://chris.beams.io/posts/git-commit/

Thank you, good work

2019-11-26 05:12 UTC, mjn0898 commented
Thanks, I will keep that in mind